   <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Lista ogłoszeń') ?></h1>
                </div>
            </div>   

    <!-- Portfolio -->
            <div class="row" style="margin-bottom:10px;">  
                <div class="large-12 columns no-padding">
                    
                    <div class="portfolio-wrapper" style="height: 200px; background: #fff !important;">

                        <div class="portfolio-item fixed-box" style="height:180px;padding: 30px 40px;">
                            <h2 class="smaller"><?php echo $this->translate('Wybierz kategorię:') ?></h2>
                            <p>
                                <?php echo $this->translate('Możesz wybrać kategorię, dzięki czemu zawęzisz obszar poszukiwań :)') ?>
                            </p>
                            <p>
                                <?php $url = $this->url('candidates', array('action' => 'offer')); ?>
                                <form id="portfolio-filter-wrapper" name="myform" class="custom" action="<?php echo $this->url('candidates', array('action' => 'offer')) ?>">
                                    <select id="portfolio-filter" name="myjumpbox" class="medium" OnChange="location.href='<?php echo $url ?>/'+myform.myjumpbox.options[selectedIndex].value">
                                        
                                        <option  value="<?php echo $url ?>" >Wszystkie kategorie</option>
                                        
                                        <?php foreach($categories as $k=>$v) :?>
                                        <option <?php echo $param == $k ? 'selected="selected"': '' ?> value="<?php echo $k ?>"><?php echo $v ?></option>
                                        <?php endforeach; ?>
                                                                       
                                    </select>
                                    
                                </form>
                            </p>
                        </div>            
                    </div>
                </div>
            </div> 
    <!--<hr style="border:0px; border-top: 1px solid #88C425; padding: 0;margin: 0;">-->
    <script>
    $("#portfolio-filterek option").change(function(){ 
        if ($(this).val()!='') { window.location.href=$(this).val(); } 
    });
    </script>