       <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Popularne') ?> <strong><?php echo $this->translate('Oferty pracy') ?></strong></h1>
                </div>
            </div>   

    <!-- Portfolio -->
            <div class="row">
                <div class="large-12 columns no-padding">
                    
                    <div class="portfolio-wrapper">

                        <div class="portfolio-item fixed-box">
                            <h2 class="smaller"><?php echo $this->translate('Wybierz kategorię:') ?></h2>
                            <p>
                                <?php echo $this->translate('Znajdź to czego szukasz :)') ?>
                            </p>
                            <p>
                                <form id="portfolio-filter-wrapper" class="custom">
                                    <select id="portfolio-filter" class="medium">
                                        <option selected="selected" value="*">Wszystkie kategorie</option>
                                        <option value=".automotive">automotive</option>
                                        <option value=".office">biuro i administracja</option>
                                        <option value=".budownictwo">budownictwo</option>
                                        <option value=".gastronomia">gastronomia</option>
                                        <option value=".hr_kadry">hr, kadry i rekrutacja</option>
                                        <option value=".telekom">telekomunikacja</option>
                                        <option value=".telemark">telemarketing i call center</option>
                                        <option value=".turystyka">turystyka</option>
                                        <option value=".tworzywa">tworzywa sztuczne</option>
                                        <option value=".energetyka">energetyka</option>
                                        <option value=".elektryka">elektryka/elektronika</option>
                                        <option value=".informatyka">informatyka</option>
                                        <option value=".logistyka">logistyka</option>
                                        <option value=".media">media</option>
                                        <option value=".medycyna">medycyna</option>
                                        <option value=".motoryzacja">motoryzacja</option>
                                        <option value=".opieka">opieka</option>
                                        <option value=".poligrafia">poligrafia</option>
                                        <option value=".produkcja">przemysł/produkcja</option>
                                        <option value=".spedycja">spedycja</option>
                                        <option value=".pomocdom">sprzątanie i pomoc domowa</option>                                      
                                    </select>
                                </form>
                            </p>
                        </div>
    
                        <div class="budownictwo gastronomia portfolio-item">
                            <div class="portfolio-item-hover">
                                <h3><a href="portfolio-single.html">Firma budowlana</a></h3>
                                <ul>
                                    <li>
                                        <a href="#">Budownictwo</a>
                                    </li>
                                    <li>
                                        <a href="#">Gastronomia</a>
                                    </li>
                                </ul>
                            </div>
                            <img src="<?php echo $this->basePath('images/placeholders/255x255.gif') ?>" alt="" class="stretch-image" />
                        </div>
                        
                        <div class="automotive office portfolio-item">
                            <div class="portfolio-item-hover">
                                <h3><a href="portfolio-single.html">Warsztat samochodowy</a></h3>
                                <ul>
                                    <li>
                                        <a href="#">Automotive</a>
                                    </li>
                                    <li>
                                        <a href="#">Biuro i administracja</a>
                                    </li>
                                </ul>
                            </div>
                            <img src="<?php echo $this->basePath('images/placeholders/255x255.gif') ?>" alt="" class="stretch-image" />
                        </div>
                                                <div class="automotive office portfolio-item">
                            <div class="portfolio-item-hover">
                                <h3><a href="portfolio-single.html">Warsztat samochodowy</a></h3>
                                <ul>
                                    <li>
                                        <a href="#">Automotive</a>
                                    </li>
                                    <li>
                                        <a href="#">Biuro i administracja</a>
                                    </li>
                                </ul>
                            </div>
                            <img src="<?php echo $this->basePath('images/placeholders/255x255.gif') ?>" alt="" class="stretch-image" />
                        </div>
                        
                        <div class="automotive office portfolio-item">
                            <div class="portfolio-item-hover">
                                <h3><a href="portfolio-single.html">Warsztat samochodowy</a></h3>
                                <ul>
                                    <li>
                                        <a href="#">Automotive</a>
                                    </li>
                                    <li>
                                        <a href="#">Biuro i administracja</a>
                                    </li>
                                </ul>
                            </div>
                            <img src="<?php echo $this->basePath('images/placeholders/255x255.gif') ?>" alt="" class="stretch-image" />
                        </div>
                        
                        <div class="automotive office portfolio-item">
                            <div class="portfolio-item-hover">
                                <h3><a href="portfolio-single.html">Warsztat samochodowy</a></h3>
                                <ul>
                                    <li>
                                        <a href="#">Automotive</a>
                                    </li>
                                    <li>
                                        <a href="#">Biuro i administracja</a>
                                    </li>
                                </ul>
                            </div>
                            <img src="<?php echo $this->basePath('images/placeholders/255x255.gif') ?>" alt="" class="stretch-image" />
                        </div>
    
                    
                    </div>

                </div>
            </div> 