<?php
$title = $this->translate('Zamów usługę');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

           <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>
            
             <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Szukają Państwo pracowników do firmy i brakuje Państwu czasu na przeprowadzienie procesu rekrutacji – prosimy o kontakt !') ?></h1>
                </div>
            </div>
            
            <div class="row">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h2 class="has-line"><?php echo $this->translate('Zamów usługę') ?></h2>
                            <h3 class="light"><?php echo $this->translate('Jeśli są Państwo zainteresowani współpracą - zachęcamy do kontaktu:') ?></h3> 
                            
                             <p>
                                    <a class="flat button"><i class="icon-phone"></i>&ensp;&ensp;+48 12 307 00 99</a>
                                    
                             </p>
                             
                            <h3 class="blog-section-title"><?php echo $this->translate('Formularz Kontaktowy') ?></h3>
                            <form id="contact-form" method="post" class="validate client-form" enctype="multipart/form-data" >
                                <div class="row">
                                    <div class="large-5 columns less-padding">
                                        <label for="clientName">Firma</label>
                                        <input class="validate[required]" type="text" name="clientName" />
                                    </div>
                
                                    <div class="large-5 columns less-padding">
                                        <label for="clientPhone">Telefon</label>
                                        <input class="validate[required]" type="text" name="clientPhone" />
                                    </div>
                                </div>                                
                                <div class="row">
                                    <div class="large-5 columns less-padding">
                                        <label for="clientEmail">Email</label>
                                        <input class="validate[required,custom[email]]" type="text" name="clientEmail" />
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="large-5 columns less-padding">
                                        <label for="clientAttach">Załącznik</label>
                                        <input type="file" name="clientAttach" class="file-decor">                                   
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="large-12 columns less-padding">
                                        <label for="clientMessage">Wiadomość</label>
                                        <textarea class="validate[required]" name="clientMessage" style="height: 120px;"></textarea>
                                    </div>
                                </div>
                                
                                <div class="row">
                                    <div class="large-12 columns less-padding">                                     
                                        <div data-alert="" class="info box" style="background:none; border-color: #999999; color: #444;">
                                            <p>
                                                <?php echo $this->translate('  *Niniejszym oświadczam, że zgodnie z art. 23 ust. 1 pkt 1 ustawy z dnia 29 sierpnia 1997 r. o ochronie danych osobowych (Dz.U. z 2002 r. Nr 101, poz. 926) wyrażam zgodę na przetwarzanie wyżej wymienionych moich danych osobowych przez Winckler Personal w celach marketingowo/sprzedażowych.') ?>
                                            </p>
                                            <a href="#" class="close">×</a>
                                        </div>                                 
                                        
                                        <label class="inline-label"><input class="validate[required] checkbox" type="checkbox" name="clientAccept" value="yes"/>&emsp;<strong>Akceptuje</strong></label>                                          
                                    </div>
                                </div>
                                <br />
                                <div class="row">
                                    <div class="large-5 columns less-padding">
                                        <input type="submit" class="flat button" value="<?php echo $this->translate('Wyślij') ?>" />
                                    </div>
                                </div>
                            </form>
<!--                            <p id="f1_upload_process">Loading...<br/><img src="loader.gif" /></p>
<p id="result"></p>
                            <iframe id="upload_target" name="upload_target" src="#" style="width:0;height:0;border:0px solid #fff;"></iframe>
                            -->
                            
<!--                            <progress></progress>-->
                            
                            <div id="success" class="success box" style="display: none;">
                                <?php echo $this->translate('Niezwłocznie kontaktujemy się z Państwem w celu sprecyzowania szczegółów zlecenia oraz omówienia profilu kompetencyjnego kandydata.') ?>                                
                            </div>
                            <div id="error" class="error box" style="display: none;">
                                <?php echo $this->translate('Coś poszło nie tak ... Prosimy skontaktować się za pomocą email lub telfonicznie. Przepraszamy za problem.') ?>                               
                            </div>
                            
                        </div>
                    </div>

                </div>
            </div>
            
            
        </div>
        <!-- End id="content-container" -->
