<?php
$title = $this->translate('Praca Tymczasowa');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

           <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Praca tymczasowa') ?></h1>
                </div>
            </div>
            
            <div class="row">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h2 class="has-line"><?php echo $this->translate('Z nami poprawią Państwo konkurencyjność swojej firmy') ?></h2>
                          
                                <p>
                                    <?php echo $this->translate('Staranny dobór kandydatów i kompleksowe usługi z zakresu doradztwa zawodowego są naszymi priorytetami. Pracując z klientami i kandydatami, nauczyliśmy się zawsze znajdować optymalne rozwiązanie dla obu stron. Dzięki działalności w zakresie rekrutacji personelu stale poszerzamy naszą bazę kandydatów, co sprzyja znalezieniu odpowiednich pracowników, spełniających oczekiwania naszych kontrahentów. Skrupulatnie selekcjonujemy aplikacje kandydatów, przeprowadzamy rozmowy kwalifikacyjne, sprawdzamy referencje i przedstawiamy naszym kontrahentom tylko odpowiednie, dobrze dobrane kandydatury.') ?>
                                </p>
                                
                            <h3 class="light"><?php echo $this->translate('Praca tymczasowa') ?></h3>
                            
                                <p>
                                   <?php echo $this->translate('Praca tymczasowa to obecnie jedna z najwygodniejszych form zatrudnienia, która sprawdziła się już poza granicami naszego kraju, zaspokajając tym samym okresowe wzmożone zapotrzebowanie na personel. Rozwiązanie to stanowi nie tylko szansę rozwoju, ale również dodatkowe źródło pieniędzy dla wielu pracowników')?>
                                </p> 
                                
                                <h3 class="light"><?php echo $this->translate('Oferujemy kompleksową organizację procesu zatrudnienia pracowników tymczasowych dla branż:') ?></h3>
                                <ul>
                                    <li><?php echo $this->translate('automotive') ?></li>
                                    <li><?php echo $this->translate('budownictwo')?></li>
                                    <li><?php echo $this->translate('telekomunikacja') ?></li>
                                    <li><?php echo $this->translate('turystyka') ?></li>
                                    <li><?php echo $this->translate('tworzywa sztuczne') ?></li>  
                                    <li><?php echo $this->translate('energetyka') ?></li>
                                    <li><?php echo $this->translate('elektryka/elektronika') ?></li>
                                    <li><?php echo $this->translate('informatyka') ?></li>
                                    <li><?php echo $this->translate('logistyka') ?></li>
                                    <li><?php echo $this->translate('media') ?></li>
                                    <li><?php echo $this->translate('medycyna') ?></li>
                                    <li><?php echo $this->translate('motoryzacja') ?></li>
                                    <li><?php echo $this->translate('poligrafia') ?></li>
                                    <li><?php echo $this->translate('przemysł/produkcja') ?></li>                                    
                                </ul>
                               <h3 class="light"><?php echo $this->translate('Korzyści dla naszego Klienta') ?></h3>      
                               
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Obniżenie kosztów zatrudnienia pracowników') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Brak kosztów rekrutacji i selekcji personelu') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Możliwość natychmiastowej wymiany lub doboru kolejnych pracowników') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Dowolny czas trwania umowy z pracownikiem, krótkie okresy wypowiedzenia') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Przejęcie obowiązków pracodawcy w kwestii: umów, ZUS, ubezpieczenia, list obecności, wypłat, badań lekarskich oraz BHP') ?></p>
                               </blockquote>
                           
                            

                             <h3 class="light"><?php echo $this->translate('Korzyści dla Pracownika Tymczasowego:') ?></h3> 
                            
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Elastyczność czasu pracy i okresów zatrudnienia') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Zdobywanie nowych umiejętności') ?></p>
                               </blockquote>
                               <blockquote>                                   
                                   <p><?php echo $this->translate('Możliwość pozostania na stałe w Firmie, po okresie zatrudnienia czasowego') ?></p>
                               </blockquote>
                             
                              <h3 class="light"><?php echo $this->translate('Gwarancja') ?></h3> 
                             <p>
                                 Gwarantujemy Państwu najwyższą jakość usług rekrutacyjnych, popartą indywidualnie dostosowanym okresem gwarancyjnym. Przed rozpoczęciem procesu rekrutacji stosujemy analizę, pozwalającą na dokładną ocenę oczekiwań naszych klientów i elastycznie dostosowujemy gwarancję na okres od jednego do kilkunastu tygodni w zależności od Pańskich potrzeb.
                                 
                             </p>
                             
                        </div>
                    </div>

                </div>
            </div>    
           
            
        </div>
        <!-- End id="content-container" -->
