<?php
$title = $this->translate('Poleć znajomego');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

             <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><strong><?php echo $this->translate('Poleć') ?></strong> <?php echo $this->translate(' znajomego') ?></h1>
                </div>
            </div>
            
            <div class="row">
              <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            
                            <h2 class="has-line"><?php echo $this->translate('U nas opłaca się rekomendować znajomych lub bliskich!') ?></h2>                                                      
                            
                                <p>
                                   <?php echo $this->translate('Osoby zainteresowane współpracą z Agencją Zatrudnienia Winckler Personal w charakterze opiekuna/opiekunki osób starszych prosimy o kontakt w celu przeprowadzenia rozmowy telefonicznej, podczas której weryfikujemy znajomość języka niemieckiego, następnie ustalamy termin spotkania na rozmowę kwalifikacyjną w naszym biurze w celu omówienia wszelkich szczegółów dotyczących ewentualnej wspólpracy.') ?>
                                </p>                                                          
                                    
                               
                                <p>
                                    <?php echo $this->translate('Za każdą poleconą osobę otrzymasz od nas gotówkę! Warto polecać!
Jeśli polecisz nam osobę, która zostanie zatrudniona u naszego kontrahenta i przepracuje 3 miesiące, otrzymasz od nas bon o wartości 200,00 zł, który będziesz mógł zrealizować według własnego uznania.') ?>

                                </p>
                        </div>
                    </div>

                </div>
            </div>       
            
        </div>
        <!-- End id="content-container" -->
