<?php
$title = $this->translate('Referencje');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

            <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><strong><?php echo $this->translate('Referencje') ?></strong></h1>
                </div>
            </div>

            <!-- Page Intro -->     

            <div class="row">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h2 class="has-line"><?php echo $this->translate('Wasze opinie') ?></h2>                        
                            <p>
                               Wyjechałam z firmą Winckler Personal do  pracy w grudniu 2012 roku. Było to zastępstwo, do pracy przyjechałam dzień przed wyjazdem opiekunki, która była już na miejscu, dzięki temu mogłam się wdrożyć w pracę i poznać zwyczaje panujące w domu, przez co początek pracy nie był dla mnie aż tak stresujący.
Znam język niemiecki na poziomie komunikatywnym, obawiałam się, że moja znajomość bedzie zbyt słaba. W kryzysowych sytuacjach zawsze mogłam liczyć na pomoc pań z Wincklera. Przynajmniej raz w tygodniu osoby z firmy kontaktowały się ze mną pytając czy wsztystko w porządku. Czułam, że firma dba o pracownika i że nie jestem im obojętna. Pod koniec pierwszego zlecenia rodzinie bardzo zależało, abym została dłużej. Bez problemu udało mi się przedłużyć pobyt. Jestem z tej agencji zadowolona, duży plus za kontakt z klientem.
        </p>
                            <p class="light" style="text-align: right;">Opiekunka os. starszych – Danuta K. z Rzeszowa</p>
                            <hr class="thin divider">
                    
                            <p>
                               Zanim zaczęłam pracę w Winckler Personal wyjeżdżałam do pracy w Austrii prywatnie. Po problemach jakie spotkały mnie na ostatniej opiece zdecydowałam się wyjechać za pośrednictwem firmy. Piszę o tym, ponieważ różnica w pracy legalnej i na czarno jest bardzo duża. Na każdym z dwóch zleceń od Winckler Personal miałam stały kontakt z paniami z biura. Pierwszy telefon był w dniu przyjazdu, kolejne raz na miesiąc, czasami częściej. Za każdym razem pytano mnie, jak sobie radzę, czy jestem zadowolona. Gdy na ostatnim zleceniu miałam zjechać 2 tygodnie wcześniej z powodów rodzinnych, nie było problemów ze skróceniem pobytu.
Jak dotąd jestem usatysfakcjonowana pracą w Winckler Personal. Mam nadzieję, że moja opinia będzie pomocna dla innych opiekunek.
                            </p>
                            <p class="light" style="text-align: right;">Opiekunka os. starszych – Franciszka P.  z Krakowa</p>
                            <hr class="thin divider">
                            <p>
                              Z pracy na terenie Niemiec jak i również z kwatery jestem zadowolony. Otrzymałem możliwość pracy codziennie 2 godziny dłużej ażeby mieć możliwości wyjazdu co miesiąc na parę dni do Polski. Z takiego rozwiązania jestem zadowolony. Za wszystko dziękuję, myślę że będziemy w kontakcie.

                            </p>
                            <p class="light" style="text-align: right;">Lakiernik przemysłowy - Zbigniew J., ze Starego Miasta</p>
                            <hr class="thin divider">
                            <p>
                              Dzięki Agencji Winckler po długich poszukiwaniach wreszcie znalazłem pracę w Niemczech.
Jestem zadowolony z mojej pracy. Pracuję na 6 miesięcznym okresie próbnym w niemieckiej firmie
i już teraz wiem, że po tym okresie dostanę umowę na czas nieokreślony. Pracuje ze mną wielu
Polaków, prawie wszyscy znaleźli zatrudnienie dzięki Wincklerowi. Polecam tą agencję, gdyż
mamy pewność że trafimy do uczciwego niemieckiego pracodawcy i mamy dużą szansę otrzymać
pracę na stałe. Jeśli chodzi o zarobki to wszystko się zgadza się ze wcześniejszymi ustaleniami.
Można też pracować za większą kasę, ale ciężej. Ja pracuję za 1000 Euro (po odliczeniu mieszkania), a praca do ciężkich nie należy. Pozdrawiam.
                            </p>
                            
                            <p class="light" style="text-align: right;">Pracownik produkcyjny - Maciej W. z Wąbrzeżna</p>
                            <hr class="thin divider"> 
                             <p>
                            Dzięki firmie Winckler Personal odnalazłam się w swoim życiu, pracę podjęłam w listopadzie ubiegłego roku i od tego czasu regularnie wyjeżdżam do Niemiec. Została mi przydzielona para starszych ludzi, schorowanych, ale bardzo wdzięcznych za okazane serce, u nich znalazłam drugi dom, ogólnie czuję się jak w rodzinie.
W razie jakiejkolwiek potrzeby utrzymuję z firmą kontakt telefoniczny lub mailowy i jak dotąd nie było żadnych powodów do narzekań.
A teraz to co najważniejsze, na co z pewnością wszyscy czekają : wypłata wpływa na konto regularnie i bez problemów.

                            </p>
                            <p class="light" style="text-align: right;">Opiekunka os. Starszych – Barbara L. z Zabrza</p>
                            <hr class="thin divider">   
                            
                             <p>
                             Minął rok odkąd współpracuję z firmą Winckler Personal, organizacja wyjazdu, dobór ofert jest na dobrym poziomie, na oferty nie czekałam długo. Obecnie jest to moje drugie zlecenie i bardzo sobie je chwalę, tu także trafiłam na bardzo miłych i życzliwych ludzi. W tej rodzinie jestem ponad pół roku. Bardzo profesjonalna i miła obsługa jest do dyspozycji i bez problemów można się z nimi kontaktować, a co ważne mają wiele cierpliwości oraz dokładają wszelkich starań aby wyjaśnić, ewentualny problem. Ważne też jest wynagrodzenie, które bez żadnych opóźnień wpływa na rachunek bankowy i jest zgodne z zawartą umową. Jeśli chodzi o ubezpieczenie na terenie Niemiec to nie ma z tym najmniejszych problemów.
Z czystym sumieniem mogę polecić Winckler Personal, każdemu zainteresowanemu wykonywaniem pracy opiekunki.
                            </p>
                            <p class="light" style="text-align: right;">Opiekunka os. Starszych – Joanna K. z  Trójmiasta</p>
                            <hr class="thin divider"> 
                            
                            <p>
                           
Z firmą Winckler Personal współpracuję od września 2012 i jestem bardzo zadowolona z tej współpracy. Rzetelność oraz stały kontakt pracowników z opiekunkami, zarówno podczas pobytu za granicą, jak i również w kraju należą do głównych atutów tej firmy. Możliwość podpisania i przesłania dokumentów drogą mailową/pocztową znacznie ułatwia załatwianie formalności dot. zlecenia.
                            </p>
                            <p class="light" style="text-align: right;">Opiekunka os. Starszych – Karolina M. z Wałbrzycha</p>
                             
                            
                        </div>
                    </div>

                </div>
            </div>    
            
        </div>
        <!-- End id="content-container" -->
