
<!-- Modal -->
<div class="modal fade" id="information-modal" tabindex="-1" role="dialog" aria-labelledby="information-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Informacja</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-warning fade in">
            <strong>Uwaga!</strong> To miejsce jest niestety zajęte przez firmę <span class="companyTitle"></span>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
<!--        <button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

