 <?php if ($this->pageCount): ?>
     <div class="pagination pagination-centered">
   
         <ul class="pagination">
             <!-- Previous page link -->
             <?php if (isset($this->previous)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route); ?>/<?php echo $this->action; ?>?page=<?php echo $this->previous; ?>">
                       <i class="glyphicon glyphicon-chevron-left"> </i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="glyphicon glyphicon-chevron-left"> </i>
                     </a>
                 </li>
             <?php endif; ?>

             <!-- Numbered page links -->
             <?php foreach ($this->pagesInRange as $page): ?>
                 <?php if ($page != $this->current): ?>
                     <li>
                         <a href="<?php echo $this->url($this->route);?>/<?php echo $this->action; ?>?page=<?php echo $page; ?>">
                             <?php echo $page; ?>
                         </a>
                     </li>
                 <?php else: ?>
                     <li class="active">
                         <a href="#"><?php echo $page; ?></a>
                     </li>
                 <?php endif; ?>
             <?php endforeach; ?>

             <!-- Next page link -->
             <?php if (isset($this->next)): ?>
                 <li>
                     <a href="<?php echo $this->url($this->route); ?>/<?php echo $this->action; ?>?page=<?php echo $this->next; ?>">
                         <i class="glyphicon glyphicon-chevron-right"> </i>
                     </a>
                 </li>
             <?php else: ?>
                 <li class="disabled">
                     <a href="#">
                         <i class="glyphicon glyphicon-chevron-right"> </i>
                     </a>
                 </li>
             <?php endif; ?>
         </ul>
     </div>
 <?php endif; ?>