<?php
$title = $this->translate('Personel medyczny');
$this->headTitle($title);
?>
<style>
    #content-container blockquote {padding: 5px 30px;}
</style>
<!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

            <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Praca za granicą') ?></h1>
                </div>
            </div>          
        
            
            
            <div class="row">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h3 class=" has-line"><?php echo $this->translate('W naszej bazie znajdą Państwo:') ?></h3>
                             <blockquote>
                                <p>Lekarzy</p>
                            </blockquote>
                            <blockquote>
                                <p>Asystentów lekarzy</p>
                            </blockquote>
                            <blockquote>
                                <p>Dyplomowane pielęgniarki i pielęgniarzy różnych specjalizacji</p>
                            </blockquote>
                            <blockquote>
                                <p>Dyplomowane opiekunki i opiekunów osób starszych</p>
                            </blockquote>
                            <blockquote>
                                <p>Farmaceuci</p>
                            </blockquote>
                            <blockquote>
                                <p>Sanitariuszy</p>
                            </blockquote>
                            <blockquote>
                                <p>Rehabilitantów</p>
                            </blockquote>
                            <blockquote>
                                <p>Ergoterapeutów</p>
                            </blockquote>
                            <blockquote>
                                <p>Laborantów</p>
                            </blockquote>
                            <blockquote>
                                <p>oraz pozostały personel medyczny</p>
                            </blockquote>                             
                      
                           
                            
                            <h3 ><?php echo $this->translate('Rekrutujemy personel medyczny do:') ?> </h3>
                             
                            <blockquote>
                                <p><?php echo $this->translate('Klinik') ?></p>
                            </blockquote>
                            <blockquote>
                                <p><?php echo $this->translate('Klinik prywatnych') ?></p>
                            </blockquote>
                            <blockquote>
                                <p><?php echo $this->translate('Szpitali') ?></p>
                            </blockquote>
                            <blockquote>
                                <p><?php echo $this->translate('Placówek świadczących usługi pielęgniarskie') ?></p>
                            </blockquote>
                            <blockquote>
                                <p><?php echo $this->translate('Domów seniora, zakładów opiekuńczych dla osób starszych i upośledzonych') ?></p>
                            </blockquote> 
                            <blockquote>
                                <p><?php echo $this->translate('Innych placówek medycznych') ?></p>
                            </blockquote> 
                            
                        </div>
                    </div>

                </div>
            </div>                                      
               
        </div>
        <!-- End id="content-container" -->
