<?php
// module/Album/view/offer/offer/add.phtml:

$title = 'Dodawanie nowej oferty pracy';
$this->headTitle($title);
?>
<h1><a href="<?php echo $this->url('admin', array('action'=> 'offer')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-globe"></i>&ensp;<?php echo $this->translate('Oferty pracy') ?></a> - dodawanie nowej oferty</h1>

<hr />
<style>
    .form-group .form-control { min-width: 400px;   }
    .form-group span {  display: block;  }
    .form-group textarea {  min-width: 400px;   }
    .form-group ul {list-style: none; margin: 0; padding: 0; color: #ff0000; font-size: 10px;}
    .well .form-group{ margin-bottom: 0px;}
    #submitbutton {margin-left: 15px;}
    .col-lg-10 label {padding: 5px; margin: 0px 10px 0 0; }
</style>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'addOffer')));
$form->prepare();
?>

        <?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>

        
        <?php echo $this->formHidden($form->get('offerId'));?>
        

        <div class="form-group">
             <label for="offerTitle" class="col-lg-2 control-label">Tytuł</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerTitle')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerDesc" class="col-lg-2 control-label">Opis stanowiska</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerDesc')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerRequire" class="col-lg-2 control-label">Wymagania</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerRequire')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerExtraInfo" class="col-lg-2 control-label">Dodatkowe informacje</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerExtraInfo')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerType" class="col-lg-2 control-label">Stanowisko</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerType')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCountry" class="col-lg-2 control-label">Kraj</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerCountry')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCity" class="col-lg-2 control-label">Adres (Miasto)</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerCity')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCompany" class="col-lg-2 control-label">Pracodawca</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerCompany')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerNumber" class="col-lg-2 control-label">Nr ref.</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerNumber')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCategory" class="col-lg-2 control-label">Kategoria</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerCategory')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerWebPage" class="col-lg-2 control-label">Strona www</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerWebPage')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerEmail" class="col-lg-2 control-label">Email</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerEmail')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerPhone" class="col-lg-2 control-label">Telefon</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerPhone')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerImage" class="col-lg-2 control-label">Obraz</label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerImage')); ?>
             </div>
        </div>

        <div class="well">
                <div class="form-group" id="action-buttons">
                     <div class="col-lg-offset-1 col-lg-1">
                        <a href="<?php echo $this->url('admin', array('action' => 'offer')) ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót </a>
                     </div>
                     <div class="col-lg-1">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                     </div>
                </div>
        </div>
        <?php echo $this->form()->closeTag();?>
