<?php
// module/Album/view/news/news/add.phtml:

$title = 'Dodawanie nowej wiadomości';
$this->headTitle($title);
?>
<h1><a href="<?php echo $this->url('admin', array('action'=> 'news')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-list-alt"></i>&ensp;<?php echo $this->translate('Aktualności') ?></a> - dodawanie nowej wiadomości</h1>

<hr />
<style>
    .form-group .form-control { min-width: 400px;   }
    .form-group span {  display: block;  }
    .form-group textarea {  min-width: 400px;   }
    .form-group ul {list-style: none; margin: 0; padding: 0; color: #ff0000; font-size: 10px;}
    .well .form-group{ margin-bottom: 0px;}
    #submitbutton {margin-left: 15px;}
    .col-lg-10 label {padding: 5px; margin: 0px 10px 0 0; }
</style>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('admin', array('action' => 'addNews')));
$form->prepare();
?>

        <?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>       
        <?php echo $this->formHidden($form->get('newsId'));?>        

        <div class="form-group">
             <label for="newsTitlePl" class="col-lg-3 control-label">Tytuł wiadomości</label>
             <div class="col-lg-9">
                <?php echo $this->formRow($form->get('newsTitlePl')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="newsTitleDe" class="col-lg-3 control-label">Tytuł wiadomości - (niemiecki)</label>
             <div class="col-lg-9">
                <?php echo $this->formRow($form->get('newsTitleDe')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="newsMessagePl" class="col-lg-3 control-label">Treść wiadomości</label>
             <div class="col-lg-9">
                <?php echo $this->formRow($form->get('newsMessagePl')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="newsMessageDe" class="col-lg-3 control-label">Treść wiadomości - (niemiecki)</label>
             <div class="col-lg-9">
                <?php echo $this->formRow($form->get('newsMessageDe')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="newsPicture" class="col-lg-3 control-label">Dodatkowe zdjęcie</label>
             <div class="col-lg-9">
                <?php echo $this->formRow($form->get('newsPicture')); ?>
             </div>
        </div>      
        <div class="well">
                <div class="form-group" id="action-buttons">
                     <div class="col-lg-offset-2 col-lg-1">
                        <a href="<?php echo $this->url('admin', array('action' => 'news')) ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót </a>
                     </div>
                     <div class="col-lg-1">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                     </div>
                </div>
        </div>
        <?php echo $this->form()->closeTag();?>
