<?php if(isset($paginator))   :?> 
<?php
$title = 'Wiadomości (Kandydaci)';
$this->headTitle($title);
?>
<style>
    .table {margin-top: 20px !important;}
    a i {margin-right: 5px;}
    .pagination-centered {width: 100%;text-align: center;}
    .t-center {text-align: center;}
</style>

<h1><a href="<?php echo $this->url('admin', array('action' => 'candidates')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-user"></i>&ensp;<?php echo $this->translate('Kandydaci') ?></a> - formularz kontaktowy</h1>


<br />

<?php if(count($paginator)) :?>
<table class="table table-striped">
<tr>
    <th>ID</th>
    <th>Imię i Nazwisko</th>    
    <th>Email</th>
    <th>Telefon</th>   
    <th class="t-center">Załącznik</th>
    <th>Data dodania</th>
    <th>Akcje</th>
</tr>

<?php foreach ($paginator as $p) : ?>

<tr>
    <td><?php echo $this->escapeHtml($p->candidatesId);?></td>
    <td> <a href="<?php echo $this->url('admin',
            array('action'=>'candidates', 'id' => $p->candidatesId));?>"> <?php echo $this->escapeHtml($p->candidatesName);?> </a></td>
    <td><?php echo $this->escapeHtml($p->candidatesEmail);?></td>    
    <td><?php echo $this->escapeHtml($p->candidatesPhone);?></td>
    <td class="t-center">       
        <?php echo ($p->candidatesAttach != ' '  ? '<i class="glyphicon glyphicon-ok-circle">' : '<i class="glyphicon glyphicon-remove-circle">') ?>
    </td>
    <td class="span1"><?php echo  date('d-m-Y G:i',$this->escapeHtml($p->candidatesInsert));?></td>    
    <td class="span2">
        <a href="<?php echo $this->url('admin',
            array('action'=>'candidates', 'id' => $p->candidatesId));?>" title="podgląd"><i class="glyphicon glyphicon-picture"></i></a>
        <a href="<?php echo $this->url('admin',
            array('action'=>'delCandidates', 'id' => $p->candidatesId));?>" title="usuń"><i class="glyphicon glyphicon-trash"></i></a>
    </td>
</tr>
<?php endforeach; ?>

</table>
<?php
 echo $this->paginationControl(
     
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'Admin'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'admin',
         'action' => 'candidates'
     )
 );
?>

    <?php else : ?>

<div class="well">
    <p>
       <strong> Brak wiadomości :) </strong>
    </p>
</div>

<?php endif; ?>

<?php  elseif (isset($candidates)) :?>
<?php
$title = 'Treść wiadmości';
$this->headTitle($title);
?>
<style>
    .table {margin-top: 20px !important;}
    a i {margin-right: 5px;}
    tr:after td {font-weight: bold;}
</style>

<h1><a href="<?php echo $this->url('admin', array('action' => 'candidates')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-user"></i>&ensp;<?php echo $this->translate('Kandydaci') ?></a> - treść wiadomości</h1>

<br />

<table class="table table-striped">
    <tr>
        <td>ID: </td> <td><?php echo $candidates->candidatesId ?></td>
    </tr>
    <tr>
        <td>Imię i Nazwisko: </td>   <td><?php echo $candidates->candidatesName ?></td> 
    </tr>
    <tr>
        <td>Email: </td><td><?php echo $candidates->candidatesEmail ?></td>
    </tr>
    
    <tr>
        <td>Numer telefonu: </td><td><?php echo $candidates->candidatesPhone ?></td>    
    </tr>
    <tr>
        <td>Stanowisko na które Kandydat aplikuje:</td><td><?php echo $candidates->candidatesSubject ?></td>  
    </tr>
    <tr>
        <td>Treść wiadomości: </td><td><?php echo $candidates->candidatesMessage ?></td>
    </tr>
    <tr>
        <td>Załącznik: </td>
        <td>
            <?php if ($candidates->candidatesAttach != ' ' ) { ?>
            <!-- to fix -->
            <a href="<?php echo $this->basePath('upload/candidates/'.$candidates->candidatesAttach) ?>" title="Podgląd załącznika">
                <i class="glyphicon glyphicon-file"> </i>
            </a>
            <?php } else { ?>
                <span class="label label-default"> brak załącznika </span>
            <?php }?>
        
        </td> 
    </tr>
    <tr>
        <td>Data dodania: </td><td><?php echo  date('d-m-Y G:i',$this->escapeHtml($candidates->candidatesInsert));?></td>
    </tr>
</table>
 
<div class="form-group">
    <a href="<?php echo $this->url('admin',array('action'=>'candidates')) ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót </a>
    
</div>

<?php endif; ?>


