<?php if(isset($paginator))   :?> 
<?php
$title = 'Wiadomości (Kontakt)';
$this->headTitle($title);
?>
<style>
    .table {margin-top: 20px !important;}
    a i {margin-right: 5px;}
    .pagination-centered {width: 100%;text-align: center;}
</style>

<h1><a href="<?php echo $this->url('admin', array('action' => 'contact')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-envelope"></i>&ensp;<?php echo $this->translate('Wiadomości') ?></a> - formularz kontaktowy</h1>


<br />

<?php if(count($paginator)) :?>
<table class="table table-striped">
<tr>
    <th>ID</th>
    <th>Imię i Nazwisko</th>    
    <th>Email</th>
   
    <!--<th>Stanowisko</th>-->
    <th>Data dodania</th>
    <th>Akcje</th>
</tr>

<?php foreach ($paginator as $p) : ?>

<tr>
    <td><?php echo $this->escapeHtml($p->contactId);?></td>
    <td> <a href="<?php echo $this->url('admin',
            array('action'=>'contact', 'id' => $p->contactId));?>"> <?php echo $this->escapeHtml($p->contactName);?> </a></td>
    <td><?php echo $this->escapeHtml($p->contactEmail);?></td>
    
    <!--<td><?php //echo $this->escapeHtml($p->contactPosition);?></td>-->
    <td class="span1"><?php echo  date('d-m-Y G:i',$this->escapeHtml($p->contactInsert));?></td>    
    <td class="span2">
        <a href="<?php echo $this->url('admin',
            array('action'=>'contact', 'id' => $p->contactId));?>" title="podgląd"><i class="glyphicon glyphicon-picture"></i></a>
        <a href="<?php echo $this->url('admin',
            array('action'=>'delContact', 'id' => $p->contactId));?>" title="usuń"><i class="glyphicon glyphicon-trash"></i></a>
    </td>
</tr>
<?php endforeach; ?>

</table>
<?php
 echo $this->paginationControl(
     
     $this->paginator,
     // the scrolling style
     'sliding',
     // the partial to use to render the control
     array('partial/paginator.phtml', 'Admin'),
     // the route to link to when a user clicks a control link
     array(
         'route' => 'admin',
         'action' => 'contact'
     )
 );
?>

    <?php else : ?>

<div class="well">
    <p>
       <strong> Brak wiadomości :) </strong>
    </p>
</div>

<?php endif; ?>

<?php  elseif (isset($contact)) :?>
<?php
$title = 'Treść wiadmości';
$this->headTitle($title);
?>
<style>
    .table {margin-top: 20px !important;}
    a i {margin-right: 5px;}
    tr:after td {font-weight: bold;}
</style>

<h1><h1><a href="<?php echo $this->url('admin', array('action' => 'contact')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-envelope"></i>&ensp;<?php echo $this->translate('Wiadomości') ?></a> - treść wiadomości</h1></h1>

<br />

<table class="table table-striped">
    <tr>
        <td>ID: </td> <td><?php echo $contact->contactId ?></td>
    </tr>
    <tr>
        <td>Imię i Nazwisko: </td>   <td><?php echo $contact->contactName ?></td> 
    </tr>
    <tr>
        <td>Email: </td><td><?php echo $contact->contactEmail ?></td>
    </tr>
    
<!--    <tr>
        <td>Numer telefonu: </td><td><?php // echo $contact->contactPhone ?></td>
    </tr>-->
<!--    <tr>
        <td>Stanowisko: </td><td><?php //echo $contact->contactPosition ?></td> 
    </tr>-->
    <tr>
        <td>Treść wiadomości: </td><td><?php echo $contact->contactMessage ?></td>
    </tr>
    <tr>
        <td>Data dodania: </td><td><?php echo  date('d-m-Y G:i',$this->escapeHtml($contact->contactInsert));?></td>
    </tr>
</table>
 
<div class="form-group">
    <a href="<?php echo $this->url('admin',array('action'=>'contact')) ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót </a>
    
</div>

<?php endif; ?>


