<?php
//    module/Album/view/album/album/delete.phtml:

    $title = $this->translate('usuń wiadomość');
    $this->headTitle($title);
    $url = $this->url('admin', array('action' => 'delContact','id' => $this->id));
?>
<h1><a href="<?php echo $this->url('admin', array('action' => 'contact')) ?>" class="btn btn-default btn-lg"><i class="glyphicon glyphicon-envelope"></i>&ensp;<?php echo $this->translate('Wiadomości') ?></a> - <?php echo $this->escapeHtml($title); ?></h1>
<hr />

<div class="well">
    <p>
        <?php echo $this->translate('Czy chcesz usunąć wiadomość od: ') ?><span class="info-del">'<?php echo $this->escapeHtml($contact->contactName); ?>'</span> ?
    </p>
</div>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $contact->contactId; ?>" />
        <button name="del" value="Powrót" class="btn btn-default"/><i class="glyphicon glyphicon-chevron-left"></i>&ensp;<?php echo $this->translate('Powrót') ?></button>
        <input type="submit" name="del" value="<?php echo $this->translate('Usuń') ?>" class="btn btn-danger"/>
    </div>
</form>

