<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Usuń e-mail z newslettera';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<div class="well">
    <p>
        Czy chcesz usunąć e-mail: <span class="info-del">'<?php echo $this->escapeHtml($notification->notificationEmail); ?>'</span> ?
    </p>
</div>

<?php
$url = $this->url('admin', array(
    'action' => 'delNotification',
    'id'     => $this->id,
));
?>

<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $notification->notificationId; ?>" />
    <button name="del" value="Powrót" class="btn btn-default"/><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót</button>
    <input type="submit" name="del" value="Usuń" class="btn btn-danger"/>
</div>
</form>

