<?php
    $title = $this->translate('Wizualizacja');
    $this->headTitle($title);
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin', array('action' => 'editOffer', 'id' => $id)));
    $form->prepare();
?>
<h1><a href="<?php echo $this->url('admin', array('action'=> 'offer')) ?>" class="btn btn-default btn-lg"><i class="fa fa-users"></i>&ensp;<?php echo $this->translate('Firmy') ?></a> - <?php echo $this->translate('wizualizacja firmy') ?> <span class="companyTitle"><?php echo $offer->offerTitle ?></span></h1>
<hr />

<?php 
    //messages, alerts
    echo $this->partial('partial/messages');

    $numPositions = array();
    
    foreach($this->allLocations as $p) {
         $numPositions[$p['position']] = $p['name'];
    }
    
    ?>
<div class="edit-company">
      
      <?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>        
      <?php echo $this->formHidden($form->get('offerId'));?>      
      <div class="form-group">
             <label for="offerNumber" class="col-lg-2 control-label"><?php echo $this->translate('Loaklizacja stanowiska') ?></label>
             <div class="col-lg-10">
                 <?php echo $this->formRow($form->get('offerNumber')); ?>
                 <div class="grid-chooser">
                     <table>                         
                         <tr>
                         
                         <?php for($grid = 1; $grid <= 100 ; $grid++) :?>                     
                            <td>
                                <?php if($grid == $offer->offerNumber) :?>
                                    <button class="btn btn-default btn-info" title="<?php echo $offer->offerTitle ?>" rel="tooltip" name="gridPlace" value="<?php echo $grid ?>"><i class="fa fa-check-square-o"></i></button>
                                <?php elseif(array_key_exists($grid, $numPositions)) : ?>    
                                    <button class="btn btn-inverse" title="<?php echo $numPositions[$grid] ?>" rel="tooltip" name="gridPlace" value="<?php echo $grid ?>"><i class="fa fa-check-square-o"></i></button>
                                <?php else :?>
                                    <button class="btn btn-default" title="<?php echo $grid ?>" rel="tooltip" name="gridPlace" value="<?php echo $grid ?>"><i class="fa fa-square-o"></i></button>
                                <?php endif; ?>
                            </td> 
                            <?php if($grid%10 == 0) : ?>
                                </tr><tr> 
                            <?php endif; ?>
                            
                         <?php endfor; ?>
                                    
                         </tr>
                     </table>
                 </div>
             </div>
        </div>
        <div class="form-group">
             <label for="offerNumber" class="col-lg-2 control-label"><?php echo $this->translate('Sposób prezentacji') ?></label>
             <div class="col-lg-10">
                 radio buttony
             </div>
        </div>
        <div class="form-group">
             <label for="offerNumber" class="col-lg-2 control-label"><?php echo $this->translate('Logo') ?></label>
             <div class="col-lg-10">
                 radio buttony
             </div>
        </div>
        <div class="well">
                <div class="form-group" id="action-buttons">
                     <div class="col-lg-offset-1 col-lg-1 pull-left">
                        <a href="<?php echo $this->url('admin', array('action' => 'offer')) ?>" class="btn btn-default"><i class="glyphicon glyphicon-chevron-left"></i>&ensp;Powrót </a>
                     </div>
                     <div class="col-lg-1">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                     </div>
                </div>
        </div>
        <?php echo $this->form()->closeTag();?>
    
</div>


<!-- Modal -->
<div class="modal fade" id="information-modal" tabindex="-1" role="dialog" aria-labelledby="information-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Informacja</h4>
      </div>
      <div class="modal-body">
        <div class="alert alert-warning fade in">
            <strong>Uwaga!</strong> To miejsce jest niestety zajęte przez firmę <span class="companyTitle"></span>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
<!--        <button type="button" class="btn btn-primary">Save changes</button>-->
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


