<?php if(isset($paginator)) :?>
<?php
    $title = $this->translate('Firmy/Klienci');
    $this->headTitle($title);
?>
<div class="row">
    <div class="col-md-11">
        <h1><a href="<?php echo $this->url('admin', array('action'=> 'offer')) ?>" class="btn btn-default btn-lg"><i class="fa fa-users"></i>&ensp;<?php echo $this->translate('Firmy') ?></a> - lista</h1>
    </div>
    <div class="col-md-1">
        <a href='<?php echo $this->url('admin', array('action' => 'add-offer'));?>' style="margin-top:20px" class="btn btn-primary pull-right"><?php echo $this->translate('Dodaj firmę'); ?></a>
    </div>
</div>

<?php 
    //messages, alerts
    echo $this->partial('partial/messages');
?>
<hr />
<form method="get" action="" class="search-form">
    <div class="panel panel-default">
        <div class="panel-body">
        <div class="row">        
            <div class="col-lg-6">
            <div class="input-group">        
                  <input type="text" value="<?php if(isset($_GET['s'])) {echo $_GET['s'];}?>" class="form-control" name="s" placeholder="<?php echo $this->translate('wpisz szukane słowo') ?>" <?php if(!isset($_GET['s'])) {echo 'required="required"';} ?>>
                  <input type="hidden" name="c" value="">
                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default" tabindex="-1"><?php echo $this->translate('Szukaj') ?></button>
                    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" tabindex="-1" rel="tooltip" title="wybierz kolumnę"> 
                      <span class="caret"></span>
                      <span class="sr-only">Dropdown</span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                      <li><a href="#" rel="name"><?php echo $this->translate('Nazwa firmy') ?></a></li>
                      <li><a href="#" rel="desc"><?php echo $this->translate('Opis') ?></a></li>          
                      <li class="divider"></li>
                      <li><a href="#" rel="date"><?php echo $this->translate('Data dodania') ?></a></li>    
                    </ul>
                  </div>       

                </div>
            </div>
        </div><!-- /.row -->
        </div>
    </div>
 </form>
 <hr />
 
<?php if(count($paginator)) :?>

<table class="table table-striped table-hover">
    <tr>
        <th><?php echo $this->translate('ID') ?></th>
        <th><?php echo $this->translate('Nazwa firmy') ?></th>
        <th><?php echo $this->translate('Slogan') ?></th>
        <th class="span1"><?php echo $this->translate('Data dodania') ?></th>
        <th class="span1 text-center"><?php echo $this->translate('Widoczność') ?></th>
        <th class="span1 text-center"><?php echo $this->translate('Akcje') ?></th>
    </tr>

    <?php foreach ($paginator as $p) : ?>

    <tr>
        <td><?php echo $this->escapeHtml($p->offerId);?></td>
        <td> <a href="<?php echo $this->url('admin',
                array('action'=>'offer', 'id' => $p->offerId));?>"> <?php echo $this->escapeHtml($p->offerTitle);?> </a></td>
        <td class="span1"><span class="label label-default"><?php echo  $this->escapeHtml($p->offerType);?></span></td>
        <td class="span1"><?php echo  date('d-m-Y G:i',$this->escapeHtml($p->offerInsert));?></td>  
        <td class="span1 text-center">
            <a class="change-visibility" href="<?php echo $this->url('ajax',array('action'=>'voffer', 'id' => $p->offerId));?>"><i class="fa <?php echo($p->offerVisible) ? 'fa-check-square-o' : 'fa-square-o' ?>"></i></a>
        </td>
        <td class="span1 text-center">
            <a href="<?php echo $this->url('admin',
                array('action'=>'offer', 'id' => $p->offerId));?>" rel="tooltip" title="<?php  echo $this->translate('edycja informacji') ?>"><i class="fa fa-pencil-square-o"></i>&ensp;</a>
            <a href="<?php echo $this->url('admin',
                array('action'=>'del-offer', 'id' => $p->offerId));?>" rel="tooltip" title="<?php  echo $this->translate('usuń') ?>"><i class="fa fa-trash-o"></i>&ensp;</a>
           
            <div class="btn-group">
                <a href="#" type="button" class="" data-toggle="dropdown"  rel="tooltip" title="<?php echo $this->translate('pozostałe akcje') ?>">
                    <i class="fa fa-bars"></i>                  
                </a>
                <ul class="dropdown-menu text-left">
                  <li><a href="<?php echo $this->url('admin',
                    array('action'=>'edit-offer', 'id' => $p->offerId));?>" rel="tooltip" title=""><i class="fa fa-eye"></i>&ensp;&ensp;<?php  echo $this->translate('wizualizacja') ?></a></li>
                  <li><a href="<?php echo $this->url('admin',
                    array('action'=>'message-offer', 'id' => $p->offerId));?>" rel="tooltip" title=""><i class="fa fa-envelope"></i>&ensp;&ensp;<?php  echo $this->translate('wiadomości') ?></a></li>
                  <li><a href="<?php echo $this->url('admin',
                    array('action'=>'file', 'id' => $p->offerId));?>" rel="tooltip" title=""><i class="fa fa-file-text-o"></i>&ensp;&ensp;<?php  echo $this->translate('pliki') ?></a></li>
                </ul>
            </div>
           
        </td>
    </tr>
    <?php endforeach; ?>
</table>

<?php
 echo $this->paginationControl(
     
    $this->paginator,
            'sliding',     
            array('partial/paginator.phtml', 'Admin'),
            // the route to link to when a user clicks a control link
            array(
                'route' => 'admin',
                'action' => 'offer'
            )
    );
?>

<?php else : ?>

<div class="well" style="margin-top:20px;">
    <p>
       <strong><?php echo $this->translate('Brak firm/klientów ...') ?></strong>
    </p>
</div>

<?php endif; ?>

<?php  elseif (isset($form)) :?>
<?php
    $title = $this->translate('Firmy - edycja');
    $this->headTitle($title);
    
?>

<h1><a href="<?php echo $this->url('admin', array('action'=> 'offer')) ?>" class="btn btn-default btn-lg"><i class="fa fa-users"></i>&ensp;<?php echo $this->translate('Firmy') ?></a> - edycja</h1>
<hr />
<?php 
    //messages, alerts
    echo $this->partial('partial/messages');
    
    $form = $this->form;
    $form->setAttribute('action', $this->url('admin', array('action' => 'offer',  'id' => $this->id)));
    $form->prepare();
?>
    <div class="edit-company">
        <?php echo $this->form()->openTag($form->setAttribute('class', 'form-horizontal')); ?>        
        <?php echo $this->formHidden($form->get('offerId'));?>        

        <div class="form-group">
             <label for="offerTitle" class="col-lg-2 control-label"><?php echo $this->translate('Nazwa firmy') ?></label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerTitle')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerDesc" class="col-lg-2 control-label"><?php echo $this->translate('Opis firmy') ?></label>
             <div class="col-lg-10" >
                <?php echo $this->formRow($form->get('offerDesc')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerExtraInfo" class="col-lg-2 control-label"><?php echo $this->translate('Dodatkowe informacje') ?></label>
             <div class="col-lg-10">
                <?php echo $this->formRow($form->get('offerExtraInfo')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCategory" class="col-lg-2 control-label"><?php echo $this->translate('Kategoria') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerCategory')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerCountry" class="col-lg-2 control-label"><?php echo $this->translate('Kraj') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerCountry')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerType" class="col-lg-2 control-label"><?php echo $this->translate('Slogan') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerType')); ?>
             </div>
        </div>
       
        <div class="form-group">
             <label for="offerCity" class="col-lg-2 control-label"><?php echo $this->translate('Adres') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerCity')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerStreet" class="col-lg-2 control-label"><?php echo $this->translate('Ulica i numer bud./miesz.') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerStreet')); ?>
             </div>
        </div>      
        <div class="form-group">
             <label for="offerWebPage" class="col-lg-2 control-label"><?php echo $this->translate('Strona www') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerWebPage')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerEmail" class="col-lg-2 control-label"><?php echo $this->translate('Email') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerEmail')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerPhone" class="col-lg-2 control-label"><?php echo $this->translate('Telefon') ?></label>
             <div class="col-lg-5">
                <?php echo $this->formRow($form->get('offerPhone')); ?>
             </div>
        </div>
        <div class="form-group">
             <label for="offerNumber" class="col-lg-2 control-label"><?php echo $this->translate('Skocz do') ?></label>
             <div class="col-lg-5">
                 <?php echo $this->formRow($form->get('offerNumber')); ?>     
                 <a href="<?php echo $this->url('admin', array('action' => 'edit-offer', 'id' =>  $this->id)) ?>" title="<?php echo $this->translate('przejdź do wizualiacji') ?>"class="btn btn-info" rel="tooltip"><i class="fa fa-eye"></i>&ensp;<?php echo $this->translate('wizualizacja') ?></a>
                 <a href="<?php echo $this->url('admin', array('action' => 'message-offer', 'id' =>  $this->id)) ?>" title="<?php echo $this->translate('przejdź do wiadomości') ?>"class="btn btn-info" rel="tooltip"><i class="fa fa-envelope"></i>&ensp;<?php echo $this->translate('wiadomości') ?></a>
                 <a href="<?php echo $this->url('admin', array('action' => 'file', 'id' =>  $this->id)) ?>" title="<?php echo $this->translate('przejdź do plików') ?>"class="btn btn-info" rel="tooltip"><i class="fa fa-file-text-o"></i>&ensp;<?php echo $this->translate('pliki') ?></a>
             </div>
        </div>
        
        <div class="form-group">
             <label for="offerVisible" class="col-lg-2 control-label"><?php echo $this->translate('Widoczność') ?></label>
             <div class="col-lg-5">
                 <?php echo $this->formRow($form->get('offerVisible')); ?>     
             
             </div>
        </div>
        
        <div class="form-group">
             <label for="offerVideo" class="col-lg-2 control-label"><?php echo $this->translate('Link do wideo') ?></label>
             <div class="col-lg-5">
                 <?php echo $this->formRow($form->get('offerVideo')); ?>     
             
             </div>
        </div>
       
        <div class="form-group">
             <label for="offerImage" class="col-lg-2 control-label"><?php echo $this->translate('Logo') ?></label>
             <div class="col-lg-10">
                  <?php if ($offer->offerImage) { ?>
                    <input type="hidden" value="<?php echo $offer->offerImage ?>" name="offerImage" />
                    <a href="<?php echo $this->basePath('upload/offer/'.$offer->offerImage) ?>" class="image-box" title="<?php echo $offer->offerImage ?>" id="single_image"><img src="<?php echo $this->basePath('upload/offer/'.$offer->offerImage) ?>" alt="<?php echo $offer->offerImage; ?>" class="img-thumbnail my-images" alt=""/></a>
                    <button class="btn btn-default btn-del" name='del-picture' value='yes'><i class="glyphicon glyphicon-trash"></i>&ensp;usuń zdjęcie</button>
                  <?php } else {?>                  
                    <?php echo $this->formRow($form->get('offerImage')); ?>
                  <?php } ?>                
             </div>      
        </div>

        <div class="well">
                <div class="form-group" id="action-buttons">
                     <div class="col-lg-offset-1 col-lg-1 pull-left">
                        <a href="<?php echo $this->url('admin', array('action' => 'offer')) ?>" class="btn btn-default"><i class="fa fa-angle-left"></i>&ensp;Powrót </a>
                     </div>
                     <div class="col-lg-1">
                        <?php echo $this->formSubmit($form->get('submit')); ?>
                     </div>
                </div>
        </div>
        <?php echo $this->form()->closeTag();?>
</div>

<?php endif; ?>

<script>
$(document).ready(function() {
        
        updateVisibility();
	fireFancybox();
        fireTinyMCE();
});
</script>