<?php echo $this->doctype(); ?>

<html lang="pl">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Panel administracyjny'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('keywords', 'praca magisterska')
            ->appendName('author', 'Łukasz Gielar')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon',  'href' => $this->basePath() . '/img/fav.ico'))
                        ->prependStylesheet($this->basePath() . '/css/admin.css')                        
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css') 
                        ->prependStylesheet($this->basePath() . '/css/jquery.fancybox-1.3.4.css') 
                        ->prependStylesheet($this->basePath() . '/css/validationEngine.jquery.css') 
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')                 
                        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto:100&subset=latin,latin-ext')   
                
                ?>
        
        
        

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/jquery.fancybox-1.3.4.js')                
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<?php echo $this->url('home') ?>">V-Walk</a>                 
                </div>
                <div class="navbar-collapse collapse">                    
                     <ul class="nav navbar-nav">  
                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Edycja &ensp;<b class="caret"></b></a>
                            <ul class="dropdown-menu">
                              <li <?php  echo ($_SERVER['REQUEST_URI'] == '/admin/contact' ? 'class="active"' : '') ?>><a href="<?php echo $this->url('admin', array('action' => 'contact')) ?>"><i class="glyphicon glyphicon-envelope"></i>&ensp;<?php echo $this->translate('Wiadomości') ?></a></li>                        
                              <li class="divider"></li>
                              <li class="dropdown-header">Extra actions</li>                              
                              <li><a href="#">One more separated link</a></li>
                            </ul>
                          </li>
                        <li <?php  echo ($_SERVER['REQUEST_URI'] == '/admin/news' ? 'class="active"' : '') ?>><a href="<?php echo $this->url('admin', array('action' => 'news')) ?>"><i class="glyphicon glyphicon-list-alt"></i>&ensp;<?php echo $this->translate('Aktualności') ?></a></li>              
                        <li <?php  echo ($_SERVER['REQUEST_URI'] == '/admin/settings' ? 'class="active"' : '') ?>><a href="<?php echo $this->url('admin', array('action' => 'settings')) ?>"><i class="glyphicon glyphicon-wrench"></i>&ensp;<?php echo $this->translate('Ustawienia') ?></a></li>                                  
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>asa</li>                
                    </ul>  
                    <a href="<?php echo $this->url('admin', array('action' => 'logout')) ?>" class="btn btn-default btn-sm logout-button pull-right"><?php echo $this->translate('wyloguj') ?></a>
                </div><!--/.nav-collapse -->   
            </div>
          </div>
        
        
        <div class="container">  
            
            <?php echo $this->content; ?>            
           
            <hr>
            <footer>
                <p>&copy; 2014 - Panel administracyjny <a href="<?php echo $this->url('home') ?>">V-Walk</a>.</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
