<?php echo $this->doctype(); ?>
<html lang="<?php echo $this->lang ?>">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('V-Walk '))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5')
            ->appendName('keywords', '')
            ->appendName('description',  '')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/fav_new.ico'))                                                
                        ->prependStylesheet($this->basePath() . '/css/validationEngine.jquery.css') 
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')                        
                        ->prependStylesheet($this->basePath() . '/css/reset.css')                       
                        ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' =>'https://fonts.googleapis.com/css?family=Roboto:100,300,400&subset=latin,latin-ext')) ?>
        <!-- Le scripts -->  
        
        <?php 
        
          $this->inlineScript()   
                  
            ->prependFile('http://maps.google.com/maps/api/js?sensor=false&v=3.5')  
            ->prependFile($this->basePath() . '/js/jquery.validationEngine.js')   
            ->prependFile($this->basePath() . '/js/three.walk.js') 
            ->prependFile($this->basePath() . '/js/stats.min.js')   
            ->prependFile($this->basePath() . '/js/three/examples/js/controls/OrbitControls.js') 
            ->prependFile($this->basePath() . '/js/three/examples/js/controls/FirstPersonControls.js') 
            ->prependFile($this->basePath() . '/js/three/examples/js/controls/PointerLockControls.js') 
            ->prependFile($this->basePath() . '/js/three/examples/js/Detector.js') 
            ->prependFile($this->basePath() . '/js/models/fonts/helvetiker_bold.typeface.js') 
            ->prependFile($this->basePath() . '/js/three.js')               
            //->prependFile('https://rawgithub.com/mrdoob/three.js/master/build/three.js') 
            ->prependFile($this->basePath() . '/js/THREEx.KeyboardState.js')
            ->prependFile($this->basePath() . '/js/THREEx.FullScreen.js')
            ->prependFile($this->basePath() . '/js/vwalk.js')    
            ->prependFile($this->basePath() . '/js/bootstrap.js') 
            ->prependFile($this->basePath() . '/js/jquery-ui.js');
          
          if($this->lang == 'pl') {
            
             echo  $this->inlineScript()
                        ->prependFile($this->basePath() . '/js/jquery.validationEngine-pl.js')
                        ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js');                               
            } else {
             echo  $this->inlineScript()
                        ->prependFile($this->basePath() . '/js/jquery.validationEngine-en.js')
                        ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js');    
            }
            
       
        
        
        ?>
        

    </head>
    <body class="mgr-visualization">   
         <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<?php echo $this->url('home') ?>">V-Walk</a>                 
                </div>
                <div class="navbar-collapse collapse">                    
                     <ul class="nav navbar-nav">                                   
                        <li><a href="#" class="take-snapshot"><i class="fa fa-camera"></i>&ensp;<?php echo $this->translate('Zrzut ekranu') ?></a></li>                                  
                        <li><a href="#" class="forcePause"  data-toggle="modal" data-target="#infoModal"><i class="fa fa-info-circle"></i>&ensp;<?php echo $this->translate('Instrukcja') ?></a></li>                                  
                        <li><a href="<?php echo $this->url('admin') ?>"><i class="fa fa-cogs"></i>&ensp;<?php echo $this->translate('Panel administracyjny') ?></a></li>                                                 
                    </ul>
                    <a href="#" class="expand-button pull-right" title="<?php echo $this->translate('Ukryj menu') ?>" rel="tooltip" data-placement="bottom"><i class="fa fa-expand"></i></a>
                    <!--fix-->
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><img src="<?php  echo ($this->lang == 'en') ? $this->basePath(). '/img/uk.png' : $this->basePath(). '/img/poland.png' ; ?>" alt="lang"> &ensp;<b class="caret"></b></a>
                            <ul class="dropdown-menu"> 
                              <li class="dropdown-header"><?php echo $this->translate('dostępne języki') ?></li>                     
                              <li><a class="set-language" href="#PL" rel="PL"><img src="<?php echo $this->basePath(). '/img/poland.png' ?>" alt="Polski">&ensp;<?php echo $this->translate('Polski') ?></a></li>                        
                              <li><a class="set-language" href="#UK" rel="UK"><img src="<?php echo $this->basePath(). '/img/uk.png' ?>" alt="Angielski">&ensp;<?php echo $this->translate('Angielski') ?></a></li> 
                            </ul>
                        </li>     
                        
                    </ul>
                    <!--fix-->                    
                </div>
                
            </div>
          </div>
          <div class="navbar navbar-fixed-top show-navbar-menu hidden ">
            <div class="container-row">
                <a href="#" class="expand-button pull-right" title="<?php echo $this->translate('Pokaż menu') ?>" rel="tooltip" data-placement="left"><i class="fa fa-compress"></i></a>
            </div>
          </div>
        
            <!--content-->
            <?php echo $this->content; ?>

        <footer id="footer">            
            <?php echo date('Y') ?> &copy; <?php echo $this->translate('Kraków') ?>    
            &ensp;<a href="#" data-toggle="modal" data-target="#contactModal" title="<?php echo $this->translate('Wyślij wiadomość') ?>" rel="tooltip" data-placement="right" class="btn btn-default btn-sm infoo-question"><i class="fa fa-envelope-o"></i>&ensp;<?php echo $this->translate('Kontakt'); ?></a>          
        </footer>         
        <?php echo $this->partial('partial/modal_index') ?>       
    </body>
</html>
