<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Winckler Personal - Agencja Pracy - Pośrednictwo Pracy'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5')
            ->appendName('keywords', 'winckler, personal, pośrednictwo pracy')
            ->appendName('description',  'Agencja pośrednictwa pracy z długoletnim doświadczeniem - sprawdź naszą ofertę.')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

     
        <link rel="icon" href="/images/favicon.ico" type="image/x-icon">
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/archtek-init.css')
                        ->prependStylesheet($this->basePath() . '/css/validationEngine.jquery.css') 
                        ->prependStylesheet($this->basePath() . '/css/jquery.fancybox-1.3.4.css')
                        ->prependStylesheet($this->basePath() . '/css/isotope.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')
                        ->prependStylesheet($this->basePath() . '/css/foundation.css')
                        ->prependStylesheet($this->basePath() . '/css/reset.css')                       
                        ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' =>'https://fonts.googleapis.com/css?family=Roboto:100,300,400,700&subset=latin,latin-ext')) 
                        ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' =>'https://fonts.googleapis.com/css?family=Titillium+Web:400,600&subset=latin,latin-ext')) ?>
           
          
        <!--[if IE 8]>
            <link href="css/foundation-ie8.css" rel="stylesheet">
            <link href="css/archtek-ie8.css" rel="stylesheet">
        <![endif]-->
        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/custom.modernizr.js')
        ; ?>

    </head>
    <body>
        <!-- facebook -->
        <div id="fb-root"></div>
		<script>(function(d, s, id) {
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1&appId=337175423085665";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script>
         <!-- facebook -->      
        <div id="header-container" class="content-width">
            <!-- Logo -->
            <div id="logo-wrapper">
                <div id="logo">
                    <a href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('images/logo.png') ?>" alt="Winckler Personal" />
                    </a>  
                    <p class="head-sub-title">
                        Agencja Pośrednictwa Pracy
                    </p>
                    <p class="head-title">
                        
                        Agencja Pośrednictwa Pracy<br />
                        <span>Certyfikat Krajowego Rejestru Agencji Zatrudniania – 7979</span>
                    </p>
                    
                </div>
            </div>
            
            <!-- Menu -->
            <div id="menu-wrapper">
                
                <div id="root-menu">
                 <?php echo $this->navigation()
                    ->menu('navigation')    
                    ->setUlClass('sf-menu');             
                 ?>
                </div>
            
               
            
    
                
                <nav id="mobile-menu" class="top-bar">
                    <ul class="title-area">
                        <!-- Do not remove this list item -->
                        <li class="name"></li>
                        
                        <!-- Menu toggle button -->
                        <li class="toggle-topbar menu-icon">
                            <a href="#"><span>Menu</span></a>
                        </li>
                    </ul>
                    
                    <!-- Mobile menu's container -->
                    <section class="top-bar-section"></section>
                </nav>
            
            </div>
            
            <div id="header-lang">
                <form method="post" action="<?php echo $this->url('home') ?>">
                    <button class="header-choose-lang active"  value="en_US" name="buttonLang"><img src="<?php echo $this->basePath('images/poland.png') ?>" alt="pol" /></button>
                    <button class="header-choose-lang active"  value="deu" name="buttonLang"><img src="<?php echo $this->basePath('images/germany.png') ?>" alt="deu" /></button>
                    <button class="header-choose-lang active"  value="eng" name="buttonLang"><img src="<?php echo $this->basePath('images/uk.png') ?>" alt="eng" /></button>         
                 </form>
            </div>
            
            <!-- Search -->
            <div id="header-search">
                <a id="header-search-button" href="javascript:;"><i class="icon-search"></i></a>
            </div>
            
            <div id="header-search-input-wrapper">
                <form method="post" action="<?php echo $this->url('search') ?>">
                    <input id="header-search-input" type="text" placeholder="<?php echo $this->translate('Wpisz szukane słowo ...') ?>" name="search" />
                </form>
            </div>
            
        </div> <!-- End id="header-container" -->            
              
        <div class="container">
           
            <?php echo $this->content; ?>
            
        </div> 
        <!-- facebook -->
        <div class="facebook-div">
            <div class="facebook-div-left">
                <a href="javascript:;" id="show-facebook-action"><img src="<?php echo $this->basePath('images/facebook.png') ?>" alt="" title="" /></a>
            </div>
            <div class="fb-like-box" data-href="https://pl-pl.facebook.com/pages/WINCKLER-PERSONAL/375160039243753" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-show-faces="true" data-header="false" data-stream="false" data-show-border="false"></div>            
            
        </div>       
        <!-- facebook -->
        <!-- superoffer -->
        <div class="superofferIcon" >
            <a href="javascript:;" id="show-superoffer-action"><i class="icon-info"></i></a>
        </div>
        
        <!-- superoffer -->
        
          <!-- Footer Content -->
        <div id="footer-content-container">
            <div id="footer-content-inner-wrapper" class="content-width">
                <div id="footer-content" class="row top-margin" style="padding: 20px 0;">
                    <div class="large-4 columns less-padding">
                        <img id="footer-logo" src="<?php echo $this->basePath('images/logo.png') ?>" alt="" />
                         <p>
                            <?php echo $this->translate('Zaufanie potwierdzone certyfikatami.') ?>
                         </p>   
                         <div class="fb-like" data-href="http://wincklerpersonal.pl" data-width="The pixel width of the plugin" data-height="The pixel height of the plugin" data-colorscheme="light" data-layout="button_count" data-action="like" data-show-faces="true" data-send="false"></div>
                    </div>
                    <div class="large-4 columns less-padding">
                        <h5><?php echo $this->translate('Kontakt') ?></h5>                        
                        <p>
                            ul. Bolesława Chrobrego 23<br />
                            02-479 Warszawa<br />
                            WINCKLER PERSONAL 
                        </p>
                        <ul>
                            <li>
                                <?php echo $this->translate('Tel:') ?> +48 (68) 307 00 99
                            </li>
                            <li>
                                <?php echo $this->translate('Kom:') ?> + 48 531 178 222
                            </li>
                            <li>
                                Fax: +48 12 444 70 75
                            </li>                            
                            <li>
                                Email: <a href="mailto:info@wincklerpersonal.pl">info@wincklerpersonal.pl</a>
                            </li>
                        </ul>
                    </div>
                    <div class="large-4 columns less-padding">
                        <h5><?php echo $this->translate('Napisz do nas') ?></h5>
                        <p>
                            Masz jakieś pytania, lub chcesz uzyskać więcej informacji ? Napisz do nas !  
                        </p>
                        <a href="<?php echo $this->url('contact') ?>" class="flat button">Napisz wiadomość</a>
                    </div>
                </div>
            </div>
        </div> <!-- End id="footer-content-container" -->
        
        
            <div id="intro" class="row bottom-certifactes" >
                <div class="large-12 columns">
                    
                        <a href="#"><img id="" src="<?php echo $this->basePath('images/logo_bottom_11.png') ?>" alt=""/></a>

                        <a href="#"><img id="" src="<?php echo $this->basePath('images/logo_bottom_22.png') ?>" alt="" /></a>
                        <a target="_blank" href="https://wizytowka.rzetelnafirma.pl/75Y9TGLD"><img  title="Kliknij i sprawdź status certyfikatu" alt="" src="http://aktywnybaner.rzetelnafirma.pl/ActiveBanner/GetActiveBannerImage/1/75Y9TGLD" ></a>
                </div>
            </div>
         
                            
        
        <!-- Footer Bar -->
        <div id="footer-bar-container" class="row">
            <div id="footer-bar-inner-wrapper" class="content-width">
                <div class="large-6 columns less-padding">
                    <?php echo date('Y') ?> &copy; All Rights Reserved. Winckler Personal.
                </div>
                <div class="large-6 columns less-padding">
                    <div id="footer-social">
                        <span><?php echo $this->translate('Skontaktuj się z nami:') ?></span> 
                        <ul class="bar-social">
                            <li>
                                <a href="https://pl-pl.facebook.com/pages/WINCKLER-PERSONAL/375160039243753" target="_blank"><img src="<?php echo $this->basePath('images/social/facebook-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/facebook.png') ?>" alt="Facebook" title="Facebook" /></a>
                            </li>
                            <li>
                                <a href="https://twitter.com/WincklerPersona" target="_blank"><img src="<?php echo $this->basePath('images/social/twitter-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/twitter.png') ?>" alt="Twitter" title="Twitter" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/googleplus-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/googleplus.png') ?>" alt="Google+" title="Google+" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/linkedin-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/linkedin.png') ?>" alt="LinkedIn" title="LinkedIn" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/flickr-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/flickr.png') ?>" alt="Flickr" title="Flickr" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/vimeo-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/vimeo.png') ?>" alt="Vimeo" title="Vimeo" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/youtube-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/youtube.png') ?>" alt="YouTube" title="YouTube" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/forrst-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/forrst.png') ?>" alt="Forrst" title="Forrst" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/dribbble-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/dribbble.png') ?>" alt="Dribbble" title="Dribbble" /></a>
                            </li>
                            <li>
                                <a href="#" target="_blank"><img src="<?php echo $this->basePath('images/social/rss-bw.png') ?>" alt="" title="" /><img class="hover" src="<?php echo $this->basePath('images/social/rss.png') ?>" alt="RSS" title="RSS" /></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div> <!-- End id="footer-bar-container" -->
   
        
        <?php  echo $this->inlineScript()                            
            ->prependFile($this->basePath() . '/js/archtek.js')    
            ->prependFile($this->basePath() . '/js/jquery.scrollUp.min.js')
            ->prependFile($this->basePath() . '/js/jquery.validationEngine.js')   
            ->prependFile($this->basePath() . '/js/jquery.validationEngine-pl.js')
            ->prependFile($this->basePath() . '/js/jquery.hoverdir.js')
            ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
            ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
            ->prependFile($this->basePath() . '/js/jquery.carouFredSel-6.1.0-packed.js')
            ->prependFile($this->basePath() . '/js/jquery.touchSwipe.min.js')
            ->prependFile($this->basePath() . '/js/jquery.transit.min.js')
            ->prependFile($this->basePath() . '/js/jquery.fancybox-1.3.4.js')
            ->prependFile($this->basePath() . '/js/jquery.hoverIntent.minified.js')
            ->prependFile($this->basePath() . '/js/supersubs.js')                
            ->prependFile($this->basePath() . '/js/superfish.js')
            ->prependFile($this->basePath() . '/js/jquery.backstretch.min.js')
            ->prependFile('http://maps.google.com/maps/api/js?sensor=false&v=3.5')
            ->prependFile($this->basePath() . '/js/foundation.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.js')
           // ->prependFile($this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')               
                
        ; ?>
        
      

    </body>
</html>
