<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('V-Walk '))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=5')
            ->appendName('keywords', '')
            ->appendName('description',  '')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        
        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/fav_new.ico'))                                                
                        //->prependStylesheet($this->basePath() . '/css/archtek-init.css')
                        ->prependStylesheet($this->basePath() . '/css/validationEngine.jquery.css') 
                        //->prependStylesheet($this->basePath() . '/css/jquery.fancybox-1.3.4.css')
                        //->prependStylesheet($this->basePath() . '/css/isotope.css')
                        //->prependStylesheet($this->basePath() . '/css/foundation.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ->prependStylesheet($this->basePath() . '/css/font-awesome.min.css')                        
                        ->prependStylesheet($this->basePath() . '/css/reset.css')                       
                        ->headLink(array('rel' => 'stylesheet', 'type' => 'text/css', 'href' =>'https://fonts.googleapis.com/css?family=Roboto:100,300,400&subset=latin,latin-ext')) ?>
           
          
        <!--[if IE 8]>
            
        <![endif]-->
        
        <!-- Scripts -->
        <?php //echo $this->headScript()
         //   ->prependFile($this->basePath() . '/js/custom.modernizr.js')
        ; ?>
        
           
        <?php  echo $this->inlineScript()                   
           // ->prependFile($this->basePath() . '/js/three/src/Three.js')    
          //  ->prependFile($this->basePath() . '/js/archtek.js')    
            //->prependFile($this->basePath() . '/js/jquery.scrollUp.min.js')
             ->prependFile($this->basePath() . '/js/jquery.validationEngine-pl.js')
             ->prependFile($this->basePath() . '/js/jquery.validationEngine.js')   
           
           // ->prependFile($this->basePath() . '/js/jquery.hoverdir.js')
           // ->prependFile($this->basePath() . '/js/jquery.isotope.min.js')
           // ->prependFile($this->basePath() . '/js/jquery.easing.1.3.js')
           // ->prependFile($this->basePath() . '/js/jquery.carouFredSel-6.1.0-packed.js')
           // ->prependFile($this->basePath() . '/js/jquery.touchSwipe.min.js')
           // ->prependFile($this->basePath() . '/js/jquery.transit.min.js')
          //  ->prependFile($this->basePath() . '/js/jquery.fancybox-1.3.4.js')
            //->prependFile($this->basePath() . '/js/jquery.hoverIntent.minified.js')
            //->prependFile($this->basePath() . '/js/supersubs.js')                
          //  ->prependFile($this->basePath() . '/js/superfish.js')
           // ->prependFile($this->basePath() . '/js/jquery.backstretch.min.js')
          //  ->prependFile('http://maps.google.com/maps/api/js?sensor=false&v=3.5')
          //  ->prependFile($this->basePath() . '/js/foundation.min.js')
         // ->prependFile($this->basePath() . '/js/jquery-ui-1.10.2.custom.min.js')
            ->prependFile($this->basePath() . '/js/vwalk.js')     
            ->prependFile($this->basePath() . '/js/bootstrap.js')     
            ->prependFile($this->basePath() . '/js/jquery-ui.js')       
            ->prependFile($this->basePath() . '/js/jquery-1.9.1.min.js')                               
        ; ?>
        

    </head>
    <body>   
         <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                  </button>
                  <a class="navbar-brand" href="<?php echo $this->url('home') ?>">V-Walk</a>                 
                </div>
                <div class="navbar-collapse collapse">                    
                     <ul class="nav navbar-nav">  
<!--                         <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Opcje &ensp;<b class="caret"></b></a>
                            <ul class="dropdown-menu">                              
                              <li><a href="<?php echo $this->url('admin', array('action' => 'settings')) ?>"><i class="fa fa-wrench"></i>&ensp;<?php echo $this->translate('Ustawienia') ?></a></li> 
                              <li class="divider"></li>
                              <li class="dropdown-header">Inne</li>                              
                              <li><a href="<?php echo $this->url('admin', array('action' => 'contact')) ?>"><i class="fa fa-envelope-o"></i>&ensp;<?php echo $this->translate('Formularz kontaktowy') ?></a></li>                        
                            </ul>
                          </li>                                   -->
                        <li><a href="#"><i class="fa fa-mail-reply"></i>&ensp;<?php echo $this->translate('Od początku') ?></a></li>                                  
                        <li><a href="#"><i class="fa fa-camera"></i>&ensp;<?php echo $this->translate('Zrzut ekranu') ?></a></li>                                  
                    </ul>                    
                    <a href="#" class="expand-button pull-right" title="Ukryj menu" rel="tooltip" data-placement="left"><i class="fa fa-expand"></i></a>
                </div><!--/.nav-collapse -->   
            </div>
          </div>
          <div class="navbar navbar-fixed-top show-navbar-menu hidden ">
            <div class="container-row">
                <a href="#" class="expand-button pull-right" title="Pokaż menu" rel="tooltip" data-placement="left"><i class="fa fa-compress"></i></a>
            </div>
          </div>
        
         <?php //echo $this->navigation()->menu('navigation')->setUlClass('sf-menu');   ?>
         <?php //echo $this->basePath('images/poland.png') ?>
         <?php //echo $this->url('home') ?> 
        
        
           
            <?php echo $this->content; ?>
<!--        <div class="container"><div> -->

        <div id="footer">            
            <?php echo date('Y') ?> &copy; <?php echo $this->translate('Kraków') ?>    
            &ensp;<a href="#" data-toggle="modal" data-target="#contactModal" title="Wyślij wiadomość" rel="tooltip" data-placement="right" class="btn btn-default btn-sm infoo-question"><i class="fa fa-envelope-o"></i>&ensp;<?php echo $this->translate('Kontakt'); ?></a>          
        </div> 
        
           <div class="modal fade" id="contactModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title"><?php echo $this->translate('Wypełnij formularz') ?></h4>
                </div>
                <div class="modal-body">                  
                  <form role="form" action="" method="post" class="validate contact-form-modal"> 
                        <div class="formContent"> 
                            <div class="form-group">
                              <label for="contactName"><?php echo $this->translate('Imię') ?></label>
                              <input type="text" class="validate[required] form-control" id="contactName" name="contactName" placeholder="Podaj Imię/Nick" >
                            </div>
                            <div class="form-group">
                              <label for="contactEmail"><?php echo $this->translate('E-mail') ?></label>
                              <input type="email" class="validate[required,custom[email]] form-control" id="contactEmail"  name="contactEmail" placeholder="Wpisz e-mail" >
                            </div>   
                            <div class="form-group">
                              <label for="contactMessage"><?php echo $this->translate('Wiadomość') ?></label>
                              <textarea class="validate[required] form-control" id="contactMessage" name="contactMessage" ></textarea>
                            </div>  
                        </div>                         
                    </form>                  
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal"><?php echo $this->translate('Anuluj') ?></button>
                  <button type="button" class="btn btn-primary"><?php echo $this->translate('Wyślij') ?></button>
                </div>
              </div><!-- /.modal-content -->
            </div><!-- /.modal-dialog -->
          </div><!-- /.modal -->
    </body>
</html>
