<?php
$title = $this->translate('FAQ');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330_3.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

            <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><strong><?php echo $this->translate('Najczęściej') ?></strong> <?php echo $this->translate('zadawane pytania') ?></h1>
                </div>
            </div>

            <!-- Page Content -->
            <div class="row grey-bg">
                <div class="large-9 columns white-bg">
                    <div class="accordion" data-active-index="0">
                        <h4><a href="#"><?php echo $this->translate('Czy Winckler Personal posiada Certyfikat  Ministerstwa Pracy na działalność Pośrednictwa Pracy na terenie RP ?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Winckler Personal posiada wymagany certyfikat nr 7979 wydany przez Krajowy Rejestr Agencji Zatrudnienia, który jest ogólnodostępny po kliknięciu na plik w formacie PDF.') ?>
                            </p>
                            <a href="pdf.pdf" class="flat button"><i class="icon-save"></i>&nbsp;&nbsp;<?php echo $this->translate('pobierz certyfikat') ?></a>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Czy są pobierane jakieś opłaty związane z wyjazdem?') ?></a></h4>
                        <div>
<!--                            <p>
                                <img src="<?php //echo $this->basePath('images/placeholders/510x255.gif') ?>" alt="" />
                            </p>-->
                            <p>
                                <?php echo $this->translate('Nie pobieramy żadnych opłat od kandydatów ani osób rozpoczynających pracę.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('W jakim stopniu muszę znać język niemiecki? Czy znajomość podstawowa wystarczy?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Aby wyjechać za granicę należy mieć minimum mocne podstawy języka niemieckiego. Znajomość weryfikowana jest najpierw w rozmowie telefonicznej z naszymi konsultantami, następnie na osobistym spotkaniu z rekruterem. Chcemy mieć pewność, że zatrudniane przez nas opiekunki poradzą sobie językowo w codziennych sytuacjach w Niemczech, jak np. wizyta u lekarza, zrobienie zakupów, czy odbieranie telefonów.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Na jak długo mogę wyjechać?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Z reguły opiekunki delegowane są za granicę na minimum 8 tygodni i dłużej. W wyjątkowych sytuacjach Panie wyjeżdżają również na 6 tygodni. Wszystko zależy od preferencji rodziny, u której pracuje opiekunka.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Na jakie wynagrodzenie mogę liczyć?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Wynagrodzenie zostaje ustalone dla każdej opiekunki indywidualnie i zależy ono przede wszystkim od znajomości języka niemieckiego, ale także od doświadczenia. Miesięczne zarobki w Winckler Personal wynoszą od 850 do 1350 euro netto.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Czy w trakcie zlecenia mam zapewnione wyżywienie i zakwaterowanie?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Tak, podczas trwania zlecenia nie interesują Pana (Panią) ani koszty wyżywienia, ani zakwaterowania.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Czy ta praca jest legalna? Skąd mogę mieć taką pewność?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Zatrudniamy opiekunów/opiekunki legalnie, w oparciu o umowę cywilnoprawną, którą podpisujemy zawsze przed wyjazdem opiekuna/opiekunki. Opłacamy wszelkie składki społeczne oraz podatek dochodowy. Okres pracy w naszej firmie wlicza się do stażu emerytalnego. Występujemy również o dokumenty świadczące o legalnym zatrudnieniu opiekunki czyli druk A1 wraz z Europejską Kartą Zdrowia (karta Ubezpieczenia Zdrowotnego).') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Jak wygląda czas pracy?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Każdy(-a) opiekun(-ka) ma dziennie 2-3 godziny czasu wolnego. Po indywidualnym ustaleniu z rodziną można pracować w trybie: 6 dni pracy, dzień wolnego oraz mieć 2 wolne popołudnie w tygodniu.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Jeżeli trafię do rodziny, z której nie będę zadowolona mogę zrezygnować?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('W takim przypadku należy jak najszybciej z nami się skontaktować. Nasi konsultanci są w stałym kontakcie zarówno z opiekunami/opiekunkami, jak i z rodzinami podopiecznych. Pomagamy w rozwiązywaniu problemów, a także załatwiamy drobne formalności w imieniu opiekunów/opiekunek. W przypadku jeżeli opiekun(-ka) nie czuje się na siłach aby kontynuować zlecenie organizujemy zastępstwo, opiekun(-ka) po dotrzymaniu 14-dniowego okresu wypowiedzenia (złożonego na piśmie) może wyjechać na inne zlecenie lub wrócić do kraju.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Czy podczas pobytu w Niemczech mogę iść do lekarza?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Tak, otrzyma od nas Pan(i) Kartę EKUZ, która upoważnia Pana (Panią) do bezpłatnych wizyt lekarskich na terenie całych Niemiec.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Co jeśli nie mam doświadczenia, ale znam język niemiecki?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Każda opiekunka wypełnia ankietę, w której sama określa przypadki i schorzenia, z którymi pracowała lub których mogłaby się podjąć. Nie ma możliwości, aby opiekunka bez doświadczenia została przydzielona do cięższego przypadku, ankieta służy uniknięciu tego rodzaju sytuacji.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Od czego należy rozpocząć poszukiwanie pracy w charakterze opiekunki os. starszych?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Pierwszym krokiem jest kontakt z naszym konsultantem celem weryfikacji języka niemieckiego. Odpowie on również na wszystkie Państwa pytania dotyczące współpracy, a także poprosi o wypełnienie Formularzu Zgłoszeniowego zamieszczonego w zakładce Opiekunka osób starszych. Państwu ankietę. Po otrzymaniu kompletu dokumentów, tzn. wypełnionego Formularza oraz fotografii rozpoczynamy proces rekrutacji. Z reguły od rozmowy kwalifikacyjnej do momentu wyjazdu mija okres od 1 do 2 tygodni czasami 1-2 dni.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Nie przeszedłem (-łam) pozytywnie testu językowego, co teraz?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('W naszej bazie danych odnotowujemy znajomość języka niemieckiego aplikujących kandydatów. Jeżeli nie udało się Państwu za pierwszym razem przejść pozytywnie rozmowy kwalifikacyjnej, proszę odświeżyć sobie język niemiecki najlepiej na lekcjach prywatnych i spróbować ponownie. Postęp językowy naszych kandydatów cieszy nas najbardziej chętnie umówimy się na rozmowę w języku niemieckim za miesiąc lub za dwa – wtedy również w razie potrzeby doradzimy czy należy jeszcze się poduczyć języka czy możemy już szukać pracy dla opiekunki.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Jak długo trzeba czekać na ofertę pracy?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Oferty pracy przedstawiamy na bieżąco w terminie od 2 do 14 dni  jest szansa, że opiekunka podejmie się pracy na terenie Niemiec.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Czy są zwracane koszty przejazdu do pracy i z powrotem?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Zwrot kosztów przejazdu w wysokości 80-100 euro przysługuje zawsze w przypadku wyjazdu na co najmniej 2 miesiące pracy. Nasza firma organizuje przejazd opiekunki  do Niemiec i z powrotem licencjonowanym przewoźnikiem – kupujemy bilet, dokonujemy rezerwacji również na drogę powrotną. Opiekunka otrzymuje przez nas zakupiony bilet i zawsze jest poinformowana kiedy i o jakiej porze ma wyjazd.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('W jakim systemie będzie wypłacane moje wynagrodzenie?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('Wynagrodzenie jest wypłacane w systemie miesięcznym, do 15 dnia kolejnego miesiąca.') ?>
                            </p>
                        </div>
                        <h4><a href="#"><?php echo $this->translate('Jakie dokumenty należy zabrać ze sobą do pracy za granicą?') ?></a></h4>
                        <div>
                            <p>
                                <?php echo $this->translate('- ważny dowód osobisty oraz paszport') ?><br /><?php echo $this->translate('- oryginał umowy z polską firmą.') ?>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="large-3 columns grey-bg">
                    <h3><?php echo $this->translate('Nie znalazłeś odpowiedzi na nurtujące pytanie?') ?></h3>
                    <p>
                        <?php echo $this->translate('Możesz do Nas zadzwonić lub skontaktować się za pomocą formularza, klikając w poniższy przycisk.') ?>
                    </p>
                    <a href="<?php echo $this->url('contact') ?>" class="flat button">Kontakt</a>
                </div>
            </div>
            
        </div>
        <!-- End id="content-container" -->
