<?php
$title = $this->translate('Opiekunka');
$this->headTitle($title);
?>
<!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330_2.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

            <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Opieka') ?> <strong><?php echo $this->translate('osób starszych') ?></strong></h1>
                </div>
            </div>          

            
            <div class="row">
                <div class="large-3 columns no-padding">
                    <img src="<?php echo $this->basePath('images/placeholders/f255x700.jpg') ?>" alt="" class="stretch-image" />
                </div>
                
                <div class="large-9 columns ">                    
                    <div class="row">
<!--                        <div class="large-4 columns less-padding">
                            <h4>Column 1</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        </div>
                        <div class="large-4 columns less-padding">
                            <h4>Column 2</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        </div>
                        <div class="large-4 columns less-padding">
                            <h4>Column 3</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                        </div>-->

                <div class="large-12 columns less-padding">
                            <h2 class="has-line"><?php echo $this->translate('Praca w Niemczech') ?></h2>
                            <blockquote>
                                <p>
                                    Bezpieczna i legalna praca
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    Oferty pracy na terenie całych Niemiec
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    Zatrudnienie na dogodnych warunkach
                                </p>                                
                            </blockquote>                            
                            <p>Winckler Personal to rzetelna Agencja Zatrudniania świadcząca profesjonalne usługi w zakresie legalnego zatrudniania opiekunek na terenie Niemiec. W codziennej pracy towarzyszy nam idea społecznej odpowiedzialności. Dzięki temu możemy świadczyć dla naszych kontrahentów usługi na najwyższym poziomie.   </p>
                            
                            <h3 class="light"><?php echo $this->translate('Siedziba') ?></h3>                           
                            <p>
                               Siedziba naszej firmy mieści się w Warszawie. Zajmujemy się rekrutacją opiekunek na terenie całego kraju i organizujemy ich zatrudnienie w dowolnej miejscowości w Niemczech.
Opiekunkom oferujemy legalne zatrudnienie na terenie Niemiec wraz z wszelkimi świadczeniami socjalnymi. Posiadamy również krótkoterminowe zlecenia.

                            </p>
                            <h3 class="light"><?php echo $this->translate('Profesjonalizm') ?></h3>                           
                            <p>
                              Opiekunkom oferujemy legalne zatrudnienie na terenie Niemiec wraz z wszelkimi świadczeniami socjalnymi. Posiadamy również krótkoterminowe zlecenia.
Cechuje nas profesjonalizm i indywidualne podejście do każdego kandydata.
Nasi konsultanci weryfikują kandydatów pod kątem doświadczenia w opiece nad osobami starszymi, posiadanych referencji oraz znajomości języków obcych, wiedzy z odbytych kursów i szkoleń.
                            </p>
                            
                        </div>

                    </div>
                </div>
            </div>
            
           
            
           
               
        </div>
        <!-- End id="content-container" -->