<?php
$title = $this->translate('Oferta');
$this->headTitle($title);
?>
 <!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330_4.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

             <!-- Breadcrumbs -->
            <?php
            echo $this->navigation('navigation') 
                      ->breadcrumbs()
                      ->setMinDepth(0)
                      ->setPartial('partial/breadcrumb.phtml');
            ?>

            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><strong><?php echo $this->translate('Oferta') ?></strong></h1>
                </div>
            </div>
            
            <div class="row">
              <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            
                            <h2 class="has-line"><?php echo $this->translate('Zapewniamy') ?></h2>                                                      
                             <blockquote>
                                <p>
                                   <?php echo $this->translate('Oferty pracy na terenie całych Niemiec') ?>
                                </p>                                
                            </blockquote>
                            
                            <blockquote>
                                <p>
                                   <?php echo $this->translate('Legalne i bezpieczne wyjazdy za granicę') ?>
                                </p>                                
                            </blockquote>
                            
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Sprawdzone, indywidualnie dobrane oferty pracy') ?>
                                </p>                                
                            </blockquote>
                                                        
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Opłacone składki do ZUS') ?>
                                </p>                                
                            </blockquote>
                            
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Krótkoterminowe zlecenia') ?>
                                </p>                                
                            </blockquote>
                                                        
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Pracę w systemie 2/2 , 3/3 lub 3/2 (do wyboru)') ?>
                                </p>                                
                            </blockquote>
                                                                                    
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Atrakcyjne i terminowe wynagrodzenie (ustalane indywidualnie)') ?>
                                </p>                                
                            </blockquote>
                                                                                                                
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Druk A1, ubezpieczenie zdrowotne (kartę EKUZ) na czas pobytu za granicą') ?>
                                </p>                                
                            </blockquote>
                            
                            <blockquote>
                                <p>
                                  <?php echo $this->translate('Współpracujemy z licencjonowanymi przewoźnikami, organizujemy wyjazdy od A do Z') ?>
                                </p>                                
                            </blockquote>                       
                            
                        </div>
                    </div>

                </div>
            </div> 
            
            <div class="row top-margin">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h2 class="has-line"><?php echo $this->translate('Personel i świadczone usługi') ?></h2>
                            <h3 class="light">
                               <?php echo $this->translate(' Zakres obowiązków opiekunów obejmuje opiekę i pomoc w codziennych czynnościach:') ?> <br />                              
                            </h3>
                            
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Pomoc w czynnościach toaletowych') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Dopilnowanie przyjmowania leków') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Przygotowywanie posiłków oraz w razie potrzeby karmienie podopiecznego') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Zmiana pieluch') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Robienie zakupów') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Pomoc przy wstawaniu z łóżka, ubieranie pacjenta') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Ułożenie chorego według zaleceń lekarza') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Pomoc przy poruszaniu się') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Spacery, wizyty u lekarza') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Prowadzenie gospodarstwa domowego (pranie, sprzątanie)') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Dotrzymywanie towarzystwa') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Gotowość do wstawania w nocy') ?>                                   
                                </p>                                
                            </blockquote>
                            <blockquote>
                                <p>
                                    <?php echo $this->translate('Opieka nad zwierzętami domowymi') ?>                                   
                                </p>                                
                            </blockquote>                           
                        </div>
                    </div>

                </div>
            </div>
            
             <div class="row top-margin">
                <div class="large-12 columns for-nested">

                    <div class="row">
                        <div class="large-12 columns">
                            <h2 class="has-line"><?php echo $this->translate('Wynagrodzenie') ?></h2>
                            
                                <p>
                                    Na kształtowanie wynagrodzenia opiekunki sprawującej opiekę nad osobą starszą mają wpływ różne czynniki, a decydującym z nich jest stopień znajomości języka niemieckiego, doświadczenie w opiece nad starszymi osobami oraz nakład pracy. Wysokość pensji zależy też od stopnia znajomości języka niemieckiego oraz posiadanych kwalifikacji.
                                </p>                                
                           
                              
                            
                        </div>
                    </div>

                </div>
            </div> 
            
            
        </div>
        <!-- End id="content-container" -->
