<?php
$title = $this->translate('Aktualności');
$this->headTitle($title);
?>
<!-- Header Image -->
        <div id="header-image-container">
            <div id="header-image">
                <img src="<?php echo $this->basePath('images/placeholders/2000x330.jpg') ?>" alt="" class="stretch-image" />
            </div>
        </div>

        <div id="content-container" class="content-width">

            <!-- Breadcrumbs -->
            <div class="row">
                <div id="breadcrumbs-wrapper" class="large-12 columns for-nested">
                    <span><?php echo $this->translate('Jesteś tutaj:') ?></span>
                    <ul class="breadcrumbs">
                        <li>
                            <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Strona główna') ?></a>
                        </li>
                        <?php if(isset($paginator)) :?>
                        <li class="current">
                            <a href="#"><?php echo $this->translate('Aktualności') ?></a>
                        </li> 
                        <?php else :?> 
                        <li>
                            <a href="<?php echo $this->url('news') ?>"><?php echo $this->translate('Aktualności') ?></a>
                        </li>
                        <li class="current">
                            <a href="#"><?php echo $this->translate('Podgląd wiadomości') ?></a>
                        </li> 
                        <?php endif;?>
                    </ul>
                </div>
            </div>
            
            <?php if(isset($paginator)) :?>
            <!-- Page Intro -->
            <div id="intro" class="not-homepage row">
                <div class="large-9 large-centered columns">
                    <h1><?php echo $this->translate('Aktualności') ?></h1>
                </div>
            </div>          

                    <!-- Blog List -->
            <div class="grey-bg row">
                <div class="large-12 columns for-nested">
                    <?php foreach ($paginator as $p) : ?>
                    <div class="blog-item row">
                        <div class="large-12 columns">
                            <div class="blog-meta">
                                <span class="date" style="font-size: 12px;"><?php echo  date('d-m-Y',$this->escapeHtml($p->newsInsert));?></span>                               
                            </div>
                            <hr />
                            <h2 class="blog-title"><a href="<?php echo $this->url('news',array('id' => $p->newsId));?>"><?php echo $this->escapeHtml($p->newsTitlePl);?></a></h2>
                            <p class="excerpt">
                               <?php echo $this->escapeHtml($p->newsMessagePl);?>
                            </p>
                            <a class="readmore-link" href="<?php echo $this->url('news',array('id' => $p->newsId));?>"> Więcej</a>
                        </div>                        
                    </div>
                    <?php   endforeach; ?>
                    <div class="row">
                        
                        <?php
                         echo $this->paginationControl(

                             $this->paginator,
                             // the scrolling style
                             'sliding',
                             // the partial to use to render the control
                             array('partial/paginator_news.phtml', 'News'),
                             // the route to link to when a user clicks a control link
                             array(
                                 'route' => 'news',                                
                             )
                         );
                        ?>
     
                    </div>

                </div>
                
                
            </div>
            <?php endif; ?>
                    
            <?php if(isset($news)) : ?>
                     <!-- Page Intro -->
                    <div id="intro" class="not-homepage row">
                        <div class="large-9 large-centered columns">
                            <h1><?php echo $this->translate('Treść wiadomosci') ?></h1>
                        </div>
                    </div> 
                            
                            <div class="row">

                                <div class="large-3 columns no-padding">
                                    <?php if($news->newsPicture != '') :?>
                                    <img src="<?php echo $this->basePath('upload/news/'.$news->newsPicture)?>" alt="" class="stretch-image" />
                                    <?php else : ?>
                                        <img src="<?php echo $this->basePath('images/placeholders/f255x700x2.jpg')?>" alt="" class="stretch-image" />
                                    <?php endif; ?>
                                   
                                </div>

                                <div class="large-9 columns ">                    
                                    <div class="row">         
                                        <div class="large-12 columns less-padding">
                                                    <h2 class="has-line"><?php echo $this->escapeHtml($news->newsTitlePl) ?></h2>
                                                        <p>
                                                            <?php echo $this->escapeHtml($news->newsMessagePl) ?>
                                                        </p>                                

                                                    <p class="date"><?php echo  date('d-m-Y',$this->escapeHtml($news->newsInsert));?></p>
                                                    <a href="<?php echo $this->url('news') ?>" class="flat button"><i class="icon-angle-left"></i>&ensp;&ensp;Powrót</a>
                                        </div>
                                       
                                     </div>
                                </div>
                            </div>                            
                     
                    
            <?php endif; ?>
                    
        </div>    
            
           
     
        <!-- End id="content-container" -->